name = "Articles"

[templates]
path = "tmpl"
vars = [
    { name = "Article", value = "ArticleHandlerName" },
    { name = "List", value = "ArticleListHandlerName" },
]

[[handlers]]
path = "^/(.+)/$"
handler = "ArticleHandler"
name = "ArticleHandlerName"

[[handlers]]
path = "^/$"
handler = "ArticleListHandler"
name = "ArticleListHandlerName"
