name = "Docs"

[assets]
path = "assets"

[templates]
path = "tmpl"
vars = [
    { name = "List", value = "ListHandlerName" },
    { name = "StdList", value = "StdListHandlerName" },
    { name = "Package", value = "PackageHandlerName" },
    { name = "Source", value = "SourceHandlerName" },
]

[[handlers]]
path = "^/$"
handler = "ListHandler"
name = "ListHandlerName"

[[handlers]]
path = "^/pkg/std/?"
handler = "StdListHandler"
name = "StdListHandlerName"

[[handlers]]
path = "^/pkg/(.+)"
handler = "PackageHandler"
name = "PackageHandlerName"

[[handlers]]
path = "^/src/(.+)"
handler = "SourceHandler"
name = "SourceHandlerName"
